name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: docker build -t udagram-api-feed ./udagram-api-feed
      - run: docker build -t udagram-api-user ./udagram-api-user
      - run: docker build -t udagram-frontend ./udagram-frontend
      - run: docker build -t reverseproxy ./udagram-reverseproxy
      - run: docker tag udagram-api-feed thonn/udagram-api-feed:v2
      - run: docker tag udagram-api-user thonn/udagram-api-user:v2
      - run: docker tag udagram-frontend thonn/udagram-frontend:v2
      - run: docker tag reverseproxy thonn/reverseproxy:v2
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker push thonn/udagram-api-feed:v2
      - run: docker push thonn/udagram-api-user:v2
      - run: docker push thonn/udagram-frontend:v2
      - run: docker push thonn/reverseproxy:v2